"""
Holds Variables used across the application
"""

from Utils.Enums import ComponentTypes


DEFAULT_PARSE_FUNCS = {
    "turbine_name_func": lambda col_name: "-".join(col_name.split("-")[:2]),
    "component_type_func": lambda col_name: "-".join(col_name.split("-")[2:]),
    "project_func": lambda col_name: col_name.split("-")[0],
}

USE_YAW_ERROR_DIRECTLY = ["WAK", "BTH", "BR2", "DHW", "RDG_G132_3_47"]

OEM_PROJECT_MAPPING = {
    "GE": ["DHW", "BR2", "BTH", "WAK"],
    "Vestas": ["CFW", "GSW", "PDK", "SKO", "SFK", "WHE"],
    "Siemens": ["GNT", "GNP", "KAY", "TBF", "RDG-S"],
    "Gamesa": ["RDG-T"],
}

PROJECT_SUBSETS = {
    "BR2": {
        "GE_2_72_116": ["BR2-K001", "BR2-K003"],
        "GE_2_82_127": [
            "BR2-K002",
            "BR2-K004",
            "BR2-K005",
            "BR2-K006",
            "BR2-K007",
            "BR2-K008",
            "BR2-K009",
            "BR2-K010",
            "BR2-K011",
            "BR2-K012",
            "BR2-K013",
            "BR2-K014",
            "BR2-K015",
            "BR2-K016",
            "BR2-K017",
            "BR2-K018",
            "BR2-K019",
            "BR2-K020",
        ],
    },
    "DHW": {
        "GE_2_82_127": [
            "DHW-T001",
            "DHW-T002",
            "DHW-T003",
            "DHW-T004",
            "DHW-T005",
            "DHW-T006",
            "DHW-T008",
            "DHW-T009",
            "DHW-T010",
            "DHW-T011",
            "DHW-T012",
            "DHW-T014",
            "DHW-T015",
            "DHW-T016",
            "DHW-T017",
            "DHW-T018",
            "DHW-T019",
            "DHW-T020",
            "DHW-T022",
            "DHW-T023",
            "DHW-T024",
            "DHW-T025",
            "DHW-T026",
            "DHW-T027",
            "DHW-T028",
            "DHW-T029",
            "DHW-T030",
            "DHW-T031",
            "DHW-T032",
            "DHW-T033",
            "DHW-T034",
            "DHW-T035",
            "DHW-T036",
            "DHW-T037",
            "DHW-T038",
            "DHW-T039",
            "DHW-T040",
            "DHW-T041",
            "DHW-T042",
            "DHW-T043",
            "DHW-T044",
            "DHW-T045",
            "DHW-T046",
            "DHW-T047",
            "DHW-T048",
            "DHW-T049",
            "DHW-T050",
            "DHW-T051",
            "DHW-T052",
            "DHW-T053",
            "DHW-T054",
            "DHW-T055",
            "DHW-T056",
            "DHW-T057",
            "DHW-T058",
            "DHW-T059",
            "DHW-T060",
            "DHW-T061",
            "DHW-T062",
            "DHW-T063",
            "DHW-T064",
            "DHW-T065",
            "DHW-T066",
            "DHW-T067",
            "DHW-T068",
            "DHW-T069",
            "DHW-T070",
            "DHW-T071",
            "DHW-T072",
            "DHW-T074",
            "DHW-T078",
            "DHW-T079",
            "DHW-T080",
            "DHW-T081",
            "DHW-T082",
            "DHW-T083",
            "DHW-T084",
            "DHW-T085",
            "DHW-T086",
            "DHW-T087",
            "DHW-T088",
            "DHW-T089",
            "DHW-T090",
            "DHW-T091",
            "DHW-T092",
            "DHW-T094",
            "DHW-T095",
            "DHW-T097",
            "DHW-T100",
            "DHW-T101",
            "DHW-T102",
            "DHW-T103",
            "DHW-T104",
            "DHW-T105",
            "DHW-T106",
            "DHW-T107",
            "DHW-T108",
        ],
        "GE_2_3_116": [
            "DHW-T007",
            "DHW-T013",
            "DHW-T021",
            "DHW-T073",
            "DHW-T075",
            "DHW-T076",
            "DHW-T077",
            "DHW-T093",
            "DHW-T096",
            "DHW-T098",
            "DHW-T099",
            "DHW-T109",
        ],
    },
    "GSW": {
        "V150_4_3": [
            "GSW-T001",
            "GSW-T002",
            "GSW-T003",
            "GSW-T004",
            "GSW-T005",
            "GSW-T006",
            "GSW-T007",
            "GSW-T008",
            "GSW-T009",
            "GSW-T010",
            "GSW-T011",
            "GSW-T012",
            "GSW-T013",
            "GSW-T014",
            "GSW-T016",
            "GSW-T017",
            "GSW-T018",
            "GSW-T019",
            "GSW-T020",
            "GSW-T021",
            "GSW-T022",
            "GSW-T023",
            "GSW-T024",
            "GSW-T025",
            "GSW-T026",
            "GSW-T027",
            "GSW-T028",
        ],
        "V110_2_2": [
            "GSW-T029"
        ],  # sThis is removed because T-029 does not have pitch data and therefore fails on online filtering. Re-enable line after Pitch Signals are added to PI - FBB 12/23
    },
    "RDG": {
        "S108_2_42": [
            "RDG-S001",
            "RDG-S002",
            "RDG-S003",
            "RDG-S004",
            "RDG-S005",
            "RDG-S006",
            "RDG-S007",
            "RDG-S008",
            "RDG-S009",
            "RDG-S010",
            "RDG-S011",
            "RDG-S012",
            "RDG-S013",
            "RDG-S014",
        ],
        "G132_3_47": [
            "RDG-T011",
            "RDG-T012",
            "RDG-T013",
            "RDG-T015",
            "RDG-T016",
            "RDG-T017",
            "RDG-T018",
            "RDG-T019",
            "RDG-T020",
            "RDG-T021",
            "RDG-T022",
            "RDG-T023",
            "RDG-T024",
            "RDG-T025",
            "RDG-T026",
            "RDG-T027",
            "RDG-T028",
            "RDG-T029",
            "RDG-T030",
            "RDG-T031",
            "RDG-T032",
            "RDG-T033",
            "RDG-T034",
            "RDG-T035",
            "RDG-T036",
            "RDG-T037",
            "RDG-T038",
            "RDG-T039",
            "RDG-T040",
            "RDG-T041",
            "RDG-T042",
            "RDG-T043",
            "RDG-T044",
            "RDG-T045",
            "RDG-T046",
            "RDG-T047",
            "RDG-T048",
            "RDG-T049",
            "RDG-T050",
            "RDG-T051",
            "RDG-T052",
            "RDG-T053",
            "RDG-T055",
            "RDG-T056",
            "RDG-T058",
            "RDG-T059",
            "RDG-T060",
            "RDG-T061",
        ],
    },
}

"""
KEY_TO_NAME maps raw type portions of column names 
as parsed by constants.DEFAULT_PARSE_FUNCS["component_type_func"]
to property names. helpers.component_type_map() 
uses this definition to convert
columns to property names or the reverse; property names to 
tag types strings 
"""
KEY_TO_NAME = {
    "AUX-XFMR-T-C": ComponentTypes.TRANSFORMER_AUX.value,
    "BLADE-ANGLE-A": ComponentTypes.PITCH_ANGLE_A.value,
    "BLADE-ANGLE-B": ComponentTypes.PITCH_ANGLE_B.value,
    "BLADE-ANGLE-C": ComponentTypes.PITCH_ANGLE_C.value,
    "BLADE-ANGLE-REF": ComponentTypes.PITCH_REF.value,
    "CTR-GND-T-C": ComponentTypes.CONTROL_GROUND.value,
    "CTR-HUB-T-C": ComponentTypes.CONTROL_HUB.value,
    "CTR-TOP-T-C": ComponentTypes.CONTROL_TOP.value,
    "CTR-VCP-T-C": ComponentTypes.CONTROL_VCP.value,
    "DEN-CPM-WIND-SPD-CALC": ComponentTypes.NACELLE_AD_ADJ_WIND_SPEED.value,
    "EFFICIENCY": ComponentTypes.EFFICIENCY.value,
    "ERR-CODE": ComponentTypes.FAULT_CODE.value,
    "EXPCTD-KW-CALC": ComponentTypes.EXPECTED_POWER.value,
    "GBX-LUBOIL-T-C": ComponentTypes.GEARBOX_OIL.value,
    "GBX-COOL-WTR-T-C": ComponentTypes.GEARBOX_COOLING_WATER_TEMP.value,
    "GBX-MAIN-BRG-TE-T-C": ComponentTypes.MAIN_BEARING.value,
    "GEN-BRG-DE-T-C": ComponentTypes.GENERATOR_BEARING_DRIVE_END.value,
    "GEN-BRG-NDE-T-C": ComponentTypes.GENERATOR_BEARING_NON_DRIVE_END.value,
    "GEN-COOL-WTR-T-C": ComponentTypes.GENERATOR_COOLING.value,
    "GEN-COOLING-T-C": ComponentTypes.GENERATOR_COOLING.value,
    "GEN-PHZA-T-C": ComponentTypes.GENERATOR_WINDING_PHASE_A.value,
    "GEN-PHZB-T-C": ComponentTypes.GENERATOR_WINDING_PHASE_B.value,
    "GEN-PHZC-T-C": ComponentTypes.GENERATOR_WINDING_PHASE_C.value,
    "GEN-SLIPRING-T-C": ComponentTypes.GENERATOR_SLIP_RING.value,
    "GEN-SLIP-RING-T-C": ComponentTypes.GENERATOR_SLIP_RING.value,
    "GEN-SPD-RPM": ComponentTypes.GEN_SPEED.value,
    "GEN-WND-PHZA-T-C": ComponentTypes.GENERATOR_WINDING_PHASE_A.value,
    "GEN-WND-PHZB-T-C": ComponentTypes.GENERATOR_WINDING_PHASE_B.value,
    "GEN-WND-PHZC-T-C": ComponentTypes.GENERATOR_WINDING_PHASE_C.value,
    "GEN1-T-C": ComponentTypes.GENERATOR_1_TEMPERATURE.value,
    "GEN2-T-C": ComponentTypes.GENERATOR_2_TEMPERATURE.value,
    "HS-BRG-T-C": ComponentTypes.HIGH_SPEED_BEARING.value,
    "HSS-SHFT-BRG-GE-T-1-C": ComponentTypes.HIGH_SPEED_BEARING.value,
    "HSS-SHFT-BRG-GE-T-2-C": ComponentTypes.HIGH_SPEED_BEARING.value,
    "HYD-OIL-T-C": ComponentTypes.HYDRAULIC_OIL_TEMP.value,
    "IM-SHFT-BRG-GE-T-C": ComponentTypes.INTERMEDIATE_SHAFT_BEARING_GE.value,
    "IM-SHFT-BRG-TE-T-C": ComponentTypes.INTERMEDIATE_SHAFT_BEARING_TE.value,
    "KW": ComponentTypes.ACTIVE_POWER.value,
    "LOST-ENERGY": ComponentTypes.LOST_ENERGY.value,
    "LOST-REVENUE": ComponentTypes.LOST_REVENUE.value,
    "MAIN-BRG-TE-T-C": ComponentTypes.MAIN_BEARING.value,
    "MV-XFMR-CORE-PHZA-T-C": ComponentTypes.TRANSFORMER_CORE_PHASE_A.value,
    "MV-XFMR-CORE-PHZB-T-C": ComponentTypes.TRANSFORMER_CORE_PHASE_B.value,
    "MV-XFMR-CORE-PHZC-T-C": ComponentTypes.TRANSFORMER_CORE_PHASE_C.value,
    "MV-XFMR-PHZA-T-C": ComponentTypes.TRANSFORMER_PHASE_A.value,
    "MV-XFMR-PHZB-T-C": ComponentTypes.TRANSFORMER_PHASE_B.value,
    "MV-XFMR-PHZC-T-C": ComponentTypes.TRANSFORMER_PHASE_C.value,
    "NACL-T-C": ComponentTypes.NACELLE.value,
    "RTR-INV-PHZA-T-C": ComponentTypes.ROTOR_PHASE_A.value,
    "RTR-INV-PHZB-T-C": ComponentTypes.ROTOR_PHASE_B.value,
    "RTR-INV-PHZC-T-C": ComponentTypes.ROTOR_PHASE_C.value,
    "SEVERITY": ComponentTypes.SEVERITY.value,
    "SPINNER-T-C": ComponentTypes.HUB.value,
    "STATE": ComponentTypes.OPERATING_STATE.value,
    "TURB-STATE-SCADA": ComponentTypes.TURBINE_STATE_SCADA.value,
    "WIND-DIR": ComponentTypes.NACELLE_WIND_DIRECTION.value,
    "WIND-SPD": ComponentTypes.NACELLE_WIND_SPEED.value,
    "CNTLR-EST-WIND-SPD": ComponentTypes.NACELLE_ESTIMATED_WIND_SPEED.value,
    "XFMR1-HS-WND0-T-C": ComponentTypes.TRANSFORMER_HIGH_SPEED_WINDING_1.value,
    "XFMR2-HS-WND0-T-C": ComponentTypes.TRANSFORMER_HIGH_SPEED_WINDING_2.value,
    "YAW-DIR": ComponentTypes.YAW_POSITION.value,
    "YAW-ERROR": ComponentTypes.YAW_ERROR.value,
}

"""List of Transformer Component Types - Jylen Tate"""

TRANSFORMER_COMPONENTS = {
    ComponentTypes.TRANSFORMER_PHASE_A.value,
    ComponentTypes.TRANSFORMER_PHASE_B.value,
    ComponentTypes.TRANSFORMER_PHASE_C.value,
    ComponentTypes.TRANSFORMER_CORE_PHASE_A.value,
    ComponentTypes.TRANSFORMER_CORE_PHASE_B.value,
    ComponentTypes.TRANSFORMER_CORE_PHASE_C.value,
    ComponentTypes.TRANSFORMER_CORE_PHASE_TEMP_DEV.value,
    ComponentTypes.TRANSFORMER_PHASE_TEMP_DEV.value
}